config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root to: 'posts#index'
    resources :posts
    resources :product_types
    resources :categories
  end


  root to: 'posts#index'

  resources :product_types, only: [:index, :show]
  resources :categories, only: [:index, :show, :new]
  resources :posts, only: [:index, :show]

  resources :categories do
    resources :product_types
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :product_type

mount_uploader :picture, PictureUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :long_description, presence: true
  validates :product_type_id, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
has_many :product_types
has_many :posts, through: :product_types

validates :name, presence: true

end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product_category
  has_many :posts

  validates :name, presence: true
  validates :product_category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    layout 'admin'
    
    before_action :authenticate
    
    def authenticate
        if not user_signed_in?
            redirect_to new_user_session_path
          end
    end
end
    

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = ProductCategory.all
  end

  def new
    @category = ProductCategory.new
  end

  def create
    @category = ProductCategory.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "Pomyślnie dodano kategorię"
    else
    render action: :new
    end
  end

  def edit
  end

  private
  def category_params
    params.require(:category).permit(
      :name,
    )
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
    redirect_to admin_posts_path, notice: "Pomyślnie dodano post"
    else
    render action: :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to admin_posts_path, notice: "Pomyślnie zaktualizowano produkt"
    else
      render action: :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :description,
      :long_description,
      :product_type_id,
      :picture
    )
  end

end

app/controllers/admin/product_types_controller.rb
class Admin::ProductTypesController < Admin::BaseController
  def index
    @product_types = ProductType.all
  end

  def new
    @product_type = ProductType.new
  end

  def create
    @product_type = ProductType.new(product_type_params)
    if @product_type.save
      redirect_to admin_product_types_path, notice: "Pomyślnie dodano nowy typ produktu"
      else
      render action: :new
      end
  end

  def edit
    @product_type = ProductType.find(params[:id])
  end

  def update
    @product_type = ProductType.find(params[:id])
    if @product_type.update_attributes(product_type_params)
      redirect_to admin_product_types_path, notice: "Pomyślnie zaktualizowano typ produktu"
    else
      render action: :edit
    end
  end

  private
  def product_type_params
    params.require(:product_type).permit(
      :name,
      :product_category_id
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @product_categories = ProductCategory.all
  end

  def show
    @product_category = ProductCategory.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if not user_signed_in?
      redirect_to new_user_session_path
    end

    @posts = Post.order(created_at: :desc).limit(9)
  end

  def show
    @post = Post.find(params[:id])
    @product_type = @post.product_type
  end
  
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  def index
    @category = ProductCategory.find(params[:category_id])
    @product_types = ProductType.all
    @category_posts = ProductCategory.find(params[:category_id]).posts.order(created_at: :desc)
  end

  def show
    @product_type = ProductType.find(params[:id])
    @posts = @product_type.posts.page(params[:page]).order(created_at: :desc).per(6)
  end

  def edit
  end
  
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/product_types_helper.rb
module Admin::ProductTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/admin/categories/_category_form.html.erb
<%= simple_form_for [:admin, @category] do |f| %>
<div class="form-group">
 <%= f.input :name %>
   </div>

   <div>
 <%= f.submit "Zapisz", class: "btn btn-primary" %>
  <%= link_to "Anuluj", :back %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Admin::Categories#edit</h1>
<p>Find me in app/views/admin/categories/edit.html.erb</p>

app/views/admin/categories/index.html.erb
<h2>Kategoria</h2>



<div>
  <table class="table table-striped">
  <thead>
  <tr>
  <th>Tytuł</th>
  <th>Akcje</th>
  <th></th>
  </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
          <td>
            <%= category.name %>
          </td>
          <td>
            <%= link_to "Edycja", edit_admin_category_path(category), class: "btn btn-default btn-xs" %>
            <%= link_to "Usuń", admin_category_path(category), method: :delete,  class: "btn btn-danger btn-xs", data: {confirm: 'Czy na pewno chcesz usunać post?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

<div>
  <%= link_to new_admin_category_path, class: "btn btn-primary" do %>
  <span class="fa fa-plus"></span> Dodaj nową kategorię
  <% end %>
</div>

app/views/admin/categories/new.html.erb
<h2>Nowa kategoria</h2>
<%= render partial: "category_form" %>

app/views/admin/posts/_post_form.html.erb
<%= simple_form_for [:admin, @post] do |f| %>
<div class="form-group">
 <%= f.input :title %>
 <%= f.input :description %>
 <%= f.input :long_description %>
<%= f.file_field :picture, :label => 'Your avatar please' %>
 <%= f.association :product_type %>
   </div>

   <div>
 <%= f.submit "Zapisz", class: "btn btn-primary" %>
  <%= link_to "Anuluj", :back %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h2>Edycja posta</h2>
<%= render partial: "post_form" %>

app/views/admin/posts/index.html.erb
<h2>Posty</h2>



<div>
  <table class="table table-striped">
  <thead>
  <tr>
  <th>Tytuł</th>
  <th>Typ produktu</th>
  <th>Akcje</th>
  <th></th>
  </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
          <td>
            <%= post.title %>
          </td>
          <td>
            <%= post.product_type.name %>
          </td>
          <td>
            <%= link_to "Edycja", edit_admin_post_path(post), class: "btn btn-default btn-xs" %>
            <%= link_to "Usuń", admin_post_path(post), method: :delete,  class: "btn btn-danger btn-xs", data: {confirm: 'Czy na pewno chcesz usunać post?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

<div>
  <%= link_to new_admin_post_path, class: "btn btn-primary" do %>
  <span class="fa fa-plus"></span> Dodaj nowy post
  <% end %>
</div>

app/views/admin/posts/new.html.erb
<h2>Nowy post</h2>
<%= render partial: "post_form" %>

app/views/admin/product_types/_product_types_form.html.erb
<%= simple_form_for [:admin, @product_type] do |f| %>
<div class="form-group">
 <%= f.input :name %>
 <%= f.association :product_category %>
   </div>

   <div>
 <%= f.submit "Zapisz", class: "btn btn-primary" %>
  <%= link_to "Anuluj", :back %>
  </div>
<% end %>

app/views/admin/product_types/edit.html.erb
<h2>Edytuj typ produktu </h2>
<%= render partial: "product_types_form" %>

app/views/admin/product_types/index.html.erb
<h2>Typy produktów</h2>



<div>
  <table class="table table-striped">
  <thead>
  <tr>
  <th>Tytuł</th>
  <th>Kategoria produktu</th>
  <th>Akcje</th>
  <th></th>
  </tr>
  </thead>
  <tbody>
    <% @product_types.each do |pt| %>
      <tr>
          <td>
            <%= pt.name %>
          </td>
          <td>
            <%= pt.product_category.name %>
          </td>
          <td>
            <%= link_to "Edycja", edit_admin_product_type_path(pt), class: "btn btn-default btn-xs" %>
            <%= link_to "Usuń", admin_product_type_path(pt), method: :delete,  class: "btn btn-danger btn-xs", data: {confirm: 'Czy na pewno chcesz usunać post?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

<div>
  <%= link_to new_admin_product_type_path, class: "btn btn-primary" do %>
  <span class="fa fa-plus"></span> Dodaj nowy typ produktu
  <% end %>
</div>

app/views/admin/product_types/new.html.erb
<h2>Nowy typ produktu </h2>
<%= render partial: "product_types_form" %>

app/views/categories/index.html.erb
<h1><%= product_categories.name %></h1>
<p>Find me in app/views/categories/index.html.erb</p>



<p> <%= @product_categories.name %>    </p>

app/views/categories/show.html.erb
<h1><%= @product_category.name %></h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/posts/_posts.html.erb
<% posts.each_slice(6) do |slice|%>

	<div class="row row-flex">
		<% slice.each do |post| %>
			<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="thumbnail">
					<%= link_to posts_path do %>
						<%= image_tag post.picture, style: 'height:100px; width:100px;' %>
					<% end %> 
					<div class="caption">
						<p class="title"><%=  link_to truncate(post.title, length: 50), post_path(post), class:"a-primary"%></p>
						<p><%= simple_format(truncate(post.description, length: 30)) %></p>
						<% if user_signed_in? %>
							<%= link_to "Szczegóły", posts_path, class:"btn btn-default"%>
						<% else %>
							<p class=”lead”>
							Musisz się zalogować, aby dodać wpis.
							<%= link_to "Zaloguj się", new_user_session_path %>
							</p>
						<% end %>
						<p></p>
					</div>
				</div>
			</div>
		<% end %>

	</div>
<% end %>

app/views/posts/index.html.erb
<%= render partial: 'posts', locals: {posts: @posts } %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/product_types/edit.html.erb
<h1>ProductTypes#edit</h1>
<p>Find me in app/views/product_types/edit.html.erb</p>

app/views/product_types/index.html.erb
<h3>Posty w kategorii: <%= @category.name %> </h3>

<%= render partial: 'posts/posts', locals: {posts: @category_posts } %>

app/views/product_types/show.html.erb
<h3><%= @product_type.name %></h3>

<%= render partial: 'posts/posts', locals: {posts: @posts } %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<%= link_to t(".sign_in", :default => "Zaloguj"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to t(".sign_up", :default => "Rejestracja"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
<%= link_to t(".forgot_your_password", :default => "Nie pamiętasz hasła?"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to t('.didn_t_receive_confirmation_instructions', :default => "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to t('.didn_t_receive_unlock_instructions', :default => "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
  <%= link_to t('.sign_in_with_provider', :provider => provider.to_s.titleize, :default => "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>