config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root to: 'posts#index'
    resources :posts
    resources :product_types
    resources :categories
  end


  root to: 'posts#index'

  resources :product_types, only: [:index, :show]
  resources :categories, only: [:index, :show, :new]
  resources :posts, only: [:index, :show]

  resources :categories do
    resources :product_types
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :product_type

mount_uploader :picture, PictureUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :long_description, presence: true
  validates :product_type_id, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
has_many :product_types
has_many :posts, through: :product_types

validates :name, presence: true

end

app/models/product_type.rb
class ProductType < ApplicationRecord
  belongs_to :product_category
  has_many :posts

  validates :name, presence: true
  validates :product_category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    layout 'admin'
    
    before_action :authenticate
    
    def authenticate
        if not user_signed_in?
            redirect_to new_user_session_path
          end
    end
end
    

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = ProductCategory.all
  end

  def new
    @category = ProductCategory.new
  end

  def create
    @category = ProductCategory.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "Pomyślnie dodano kategorię"
    else
    render action: :new
    end
  end

  def edit
  end

  private
  def category_params
    params.require(:category).permit(
      :name,
    )
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
    redirect_to admin_posts_path, notice: "Pomyślnie dodano post"
    else
    render action: :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to admin_posts_path, notice: "Pomyślnie zaktualizowano produkt"
    else
      render action: :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :description,
      :long_description,
      :product_type_id,
      :picture
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @product_categories = ProductCategory.all
  end

  def show
    @product_category = ProductCategory.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if not user_signed_in?
      redirect_to new_user_session_path
    end

    @posts = Post.order(created_at: :desc).limit(9)
  end

  def show
    @post = Post.find(params[:id])
    @product_type = @post.product_type
  end
  
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  def index
    @category = ProductCategory.find(params[:category_id])
    @product_types = ProductType.all
    @category_posts = ProductCategory.find(params[:category_id]).posts.order(created_at: :desc)
  end

  def show
    @product_type = ProductType.find(params[:id])
    @posts = @product_type.posts.page(params[:page]).order(created_at: :desc).per(6)
  end

  def edit
  end
  
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/product_types_helper.rb
module Admin::ProductTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Intranet – Admin</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class='navbar navbar-inverse navbar-static-left'>
    <div class="container">
          <div class='navbar-header'>
            <%= link_to image_tag("expander-logo.png", size: "150x60", alt: "Edit Entry"), posts_path %>
          </div>

        <ul class="nav navbar-nav">
          <li <% if params[:controller] == "admin/posts" %>class="active"<% end %>><%= link_to "Posty", admin_posts_path %></li>
          <li <% if params[:controller] == "admin/categories" %>class="active"<% end %>><%= link_to "Kategorie", admin_categories_path  %></li>
          <li <% if params[:controller] == "admin/product_types" %>class="active"<% end %>><%= link_to "Typy produktów", admin_product_types_path %></li>
       
        </ul>



        <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %></li>
        </ul>
    </div>

  </nav>
  <div class="container-fluid">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intranet</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if user_signed_in?%>
      <nav class='navbar navbar-inverse navbar-static-left'>
        <div class='container'>
          <div class='navbar-header'>
            <%= image_tag("expander-logo.png", size: "150x60", alt: "Edit Entry") %>
          </div>
            <ul class='nav navbar-nav'>
              <% ProductCategory.all.each do |pc|%>
                <li <% if params[:category_id] == pc.id.to_s %> class="active" <%end%>> <%= link_to pc.name, category_product_types_path(pc.id) %> </li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Panel admina", admin_posts_path, method: :get %></li>
              <li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </nav>

        <div class='container-fluid'>
          <div class='row'>
            <div class='col-md-2'>
              <h4>Kategorie</h4>
              <ul class='nav nav-sidebar'>
                <% ProductType.where("product_category_id = ?", params[:category_id]).each do |pt|%>
                <li <% if params[:id] == pt.id.to_s %> class="active" <%end%>> <%= link_to pt.name, category_product_type_path(pt.product_category_id, pt.id) %> </li>
                <% end %>
              </ul>
            </div>
          <% end %>
            <div class='col-md-9'>
              <%= yield %>
            </div>
          </div>
        </div>

  </body>
</html>